### PR TITLE
Information

### PR DESCRIPTION
**Pull request by TannerFry**

### CODE REVIEW

**Review by 3PIV — CHANGES_REQUESTED** [review]
Hey Tanner! Would you mind adding your name in the first sentence of your .md file?

**Comment by TannerFry** [comment]
Do I need to create another pull request after updating it or just update the file and let you when it is updated?

**Comment by 3PIV** [comment]
You should be able to commit your changes and I will see the updates you make.

**Comment by 3PIV** [comment]
Actually, just comment here when you have completed your changes.

**Review by 3PIV — APPROVED** [review]
Thanks!

**Pull request merged**
